spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/bank_db
    username: bank_user
    password: bank_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
  expiration-ms: 3600000

app:
  cors:
    allowed-origins: http://localhost:3000
  seed:
    admin-username: admin
    admin-password: admin123
    user-username: user
    user-password: user123
  crypto:
    secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
